#!/usr/bin/env ruby
require 'highline/import'

if ARGV.length < 1
  print "[Help] Run as: ./ash_tray new"
elsif ARGV.length == 1
  if ARGV[0] != "new"
    print "[Help] Run as: ./ash_tray new"
  else
    choose do |menu|
      menu.prompt = ""

      menu.choice('Add a cigar') { say("") }
      menu.choice('Enter length, ring gauge, name, maker, type, location of origin, composition') { say("No cigars found. Ass a cigar.") }
      menu.choice('Exit') { say("Peace Out!\n") }
    end
  end
end
